# Makefile for MPE external using pd-lib-builder

lib.name = mpe

# Object classes (the actual externals we're creating)
class.sources = mpe-in.cpp mpe-voice.cpp

# Data files to include in the package
datafiles = mpe-in-help.pd mpe-voice-help.pd README.txt

# Use pd-lib-builder
PDLIBBUILDER_DIR=pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder